# CLPR native-queue integration destination-ledger baseline configuration
clpr.clprEnabled=true
clpr.publicizeNetworkAddresses=true
clpr.devModeEnabled=true
clpr.connectionFrequency=200
contracts.systemContract.clprQueue.enabled=true
