# CLPR native-queue integration source-ledger baseline configuration
clpr.clprEnabled=true
clpr.publicizeNetworkAddresses=false
clpr.devModeEnabled=true
clpr.connectionFrequency=200
contracts.systemContract.clprQueue.enabled=true
